# Generated by Django 2.1.4 on 2019-03-24 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text='归属产品', max_length=10, null=True, verbose_name='归属产品')),
                ('image', models.CharField(blank=True, help_text='图片地址', max_length=300, null=True, verbose_name='图片地址')),
                ('pid', models.IntegerField(blank=True, help_text='关联ID', null=True, verbose_name='关联ID')),
                ('link', models.TextField(blank=True, help_text='链接', null=True, verbose_name='链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
