# Generated by Django 2.1.4 on 2019-03-24 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, help_text='用户', max_length=60, null=True, verbose_name='用户')),
                ('content', models.TextField(blank=True, help_text='评论内容', null=True, verbose_name='评论内容')),
                ('comment_type', models.IntegerField(choices=[(1, '一级评论'), (2, '二级评论')], help_text='评论级别', verbose_name='评论级别')),
                ('thumbs_up_count', models.IntegerField(blank=True, default=10, help_text='点赞次数', null=True, verbose_name='点赞次数')),
                ('comment_time', models.DateTimeField(default=datetime.datetime.now, help_text='评论时间', verbose_name='评论时间')),
                ('reply_user', models.CharField(blank=True, help_text='被回复的用户', max_length=60, null=True, verbose_name='被回复的用户')),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=254, null=True, verbose_name='邮箱')),
                ('nickname', models.CharField(blank=True, help_text='昵称', max_length=60, null=True, verbose_name='昵称')),
                ('article_id', models.ForeignKey(blank=True, help_text='文章ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.BlogArticle', verbose_name='文章ID')),
                ('parent', models.ForeignKey(blank=True, help_text='父评论ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment.Comment', verbose_name='父评论ID')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
